import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

import Header from "@/components/header";
import Footer from "@/components/footer";
import Container from "@/components/container";

const bicubik = localFont({
    variable: '--font-bicubik',
    src: './Bicubik.otf',
});

const montserrat = Montserrat({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-montserrat',
  })
  
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${montserrat.variable} ${bicubik.variable}`}
        >
            <body>
                <ThemeProviders
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Container>
                        <Header />
                        {children}
                        <Footer />
                    </Container>
                </ThemeProviders>
            </body>
        </html>
    );
}
